// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR-64tYCNMFYE6-4qvCISjswRuKQVdtN4',
    appId: '1:669982883544:web:528c520622b1f46e7ca1ad',
    messagingSenderId: '669982883544',
    projectId: 'app-virtualloja',
    authDomain: 'app-virtualloja.firebaseapp.com',
    storageBucket: 'app-virtualloja.appspot.com',
    measurementId: 'G-YBKFLVM1SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsvSY8WGtgDPBWXrF3QiCFyOim6EGcNJI',
    appId: '1:669982883544:android:d28d479532e215807ca1ad',
    messagingSenderId: '669982883544',
    projectId: 'app-virtualloja',
    storageBucket: 'app-virtualloja.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-K93SJ5WoGADFjqbbhSKDxu_5bJNsyCc',
    appId: '1:669982883544:ios:5fd64c730afbb5067ca1ad',
    messagingSenderId: '669982883544',
    projectId: 'app-virtualloja',
    storageBucket: 'app-virtualloja.appspot.com',
    iosClientId: '669982883544-tnnlh7bm21v6kj0mkru56ogbcmnf2iof.apps.googleusercontent.com',
    iosBundleId: 'com.example.appReceitas',
  );
}
